version: "3"
services:
  elasticsearch:
    image: "elasticsearch:7.0.1"
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
  kibana:
    image: "kibana:7.0.1"
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
  logstash:
    image: "logstash:7.0.1"
    depends_on:
      - "elasticsearch"
    ports:
      - "9600:9600"
    volumes:
      - ${PWD}/countries.csv:/opt/countries.csv
      - ${PWD}/logstash_countries.conf:/usr/share/logstash/pipeline/logstash_countries.conf

